easy_admin:
    design:
          brand_color: 'black'
    entities:
            User:
                class: App\Entity\User
                list:
                      fields:
                          - id
                          - firstName
                          - lastName
                          - email
                form:
                      fields:
                          - firstName
                          - lastName
                          - email
            Champagne:
                class: App\Entity\Champagne
                list:
                      fields:
                          - name
                          - urlLink
                          - price
                          - { property: 'photo_bouteille', type: 'image', base_path: '%app.path.champagne_images%' }
                form:
                      fields:
                          - name
                          - urlLink
                          - price
                          - { property: 'type', type: 'choice', type_options: {choices: {'Classique':'Classique', 'Collection':'Collection'}}}
                          - subtitle_1
                          - presentation_1
                          - subtitle_2_1
                          - presentation_2_1
                          - subtitle_2_2
                          - presentation_2_2
                          - subtitle_2_3
                          - presentation_2_3
                          - subtitle_3
                          - presentation_3
                          - subtitle_4
                          - presentation_4
                          - { property: 'photoFile_1', type: 'vich_image' }
                          - { property: 'photoFile_2', type: 'vich_image' }
                          - { property: 'photoFile_3', type: 'vich_image' }
                          - { property: 'photoFile_paragraph_1', type: 'vich_image' }
                          - { property: 'photoFile_paragraph_2', type: 'vich_image' }
                          - { property: 'photoFile_bouteille', type: 'vich_image' }
