easy_admin:
    design:
          brand_color: 'black'
    entities:
            Champagne:
                class: App\Entity\Champagne
                list:
                    fields:
                        - { property: 'image', type: 'image', base_path: '%app.path.product_images%' }
                # ...
                show:
                    fields:
                        - { property: 'image', type: 'image', base_path: '%app.path.product_images%' }
                form:
                    fields:
                        - { property: 'imageFile', type: 'vich_image' }

