easy_admin:
    site_name: 'Philippe De Sorbon'
    design:
          brand_color: 'black'
    entities:
            User:
                label: 'Utilisateurs'
                disabled_actions: ['new', 'edit']
                class: App\Entity\User
                list:
                      fields:
                          - id
                          - { property: 'firstName', label: 'Prénom'}
                          - { property: 'lastName', label: 'Nom'}
                          - email
                          - { property: 'phoneNumber', label: 'Téléphone'}
            Champagne:
                label: 'Cuvée'
                disabled_actions: ['search']
                class: App\Entity\Champagne
                list:
                      fields:
                          - id
                          - { property: 'name', label: 'Nom'}
                          - { property: 'urlLink', label: 'Lien URL'}
                          - { property: 'price', label: 'Prix', format: "%01.2f"}
                          - { property: 'stepOrder', label: 'Bouteilles / Carton'}
                form:
                      fields:
                          - { property: 'name', label: 'Nom'}
                          - { property: 'urlLink', label: 'Lien URL'}
                          - { property: 'price', label: 'Prix', format: "%01.2f"}
                          - { property: 'stepOrder', label: 'Bouteilles / Carton'}
                          - { property: 'type',label: 'Type', type: 'choice', type_options: {choices: {'Classique':'Classique', 'Collection':'Collection'}}}
                          - { property: 'subtitle_1', label: 'Titre 1'}
                          - { property: 'presentation_1', label: 'Texte 1'}
                          - { property: 'subtitle_2_1', label: 'Titre 2.1'}
                          - { property: 'presentation_2_1', label: 'Texte 2.1'}
                          - { property: 'subtitle_2_2', label: 'Titre 2.2'}
                          - { property: 'presentation_2_2', label: 'Texte 2.2'}
                          - { property: 'subtitle_2_3', label: 'Titre 2.3'}
                          - { property: 'presentation_2_3', label: 'Texte 2.3'}
                          - { property: 'subtitle_3', label: 'Titre 3'}
                          - { property: 'subtitle_4', label: 'Titre 4'}
                          - { property: 'presentation_4', label: 'Texte 4'}
                          - { property: 'subtitle_5', label: 'Texte 5'}
                          - { property: 'presentation_5', label: 'Texte 5' }
                          - { property: 'photoFile_1', type: 'vich_image', label: "Fond d'écran 1" }
                          - { property: 'photoFile_2', type: 'vich_image', label: "Fond d'écran 2"  }
                          - { property: 'photoFile_3', type: 'vich_image', label: "Fond d'écran 3"  }
                          - { property: 'photoFile_4', type: 'vich_image', label: "Fond d'écran 4"  }
                          - { property: 'photoFile_paragraph_1', type: 'vich_image', label: "Photo paragraphe 1"  }
                          - { property: 'photoFile_paragraph_2', type: 'vich_image', label: "Photo paragraphe 2"}
                          - { property: 'photoFile_bouteille', type: 'vich_image', label: "Photo bouteille" }
            ChampagneOption:
                label: 'Modèle'
                disabled_actions: ['search']
                class: App\Entity\ChampagneOption
                list:
                      fields:
                          - { property: 'name', label: 'Nom'}
                          - { property: 'price', label: 'Prix', format: "%01.2f"}
                          - { property: 'champagne', label: 'Cuvée associée'}
                          - { property: 'stepOrder', label: 'Bouteilles / Carton' }
                form:
                      fields:
                          - { property: 'name', label: 'Nom'}
                          - { property: 'price', label: 'Prix', format: "%01.2f"}
                          - { property: 'champagne', label: 'Cuvée associée'}
                          - { property: 'stepOrder', label: 'Bouteilles / Carton' }
            Commande:
                disabled_actions: ['new', 'delete', 'edit']
                class: App\Entity\Commande
                list:
                      fields:
                          - id
                          - { property: 'buyer', label: 'Client'}
                          - { property: 'price', label: 'Total'}
                          - { property: 'paymentMethod', label: 'Moyen de paiement'}
                          - { property: 'content', label: 'Contenu'}
                          - { property: 'dateTime', label: 'Date de la commande'}
                          - { property: 'dateDelivery', label: 'Date de livraison désirée'}
                          - { property: 'addressNameDelivery', label: 'Nom'}
                          - { property: 'addressStreetDelivery', label: 'Addresse'}
                          - { property: 'addressCityDelivery', label: 'Ville'}
                          - { property: 'addressZipCodeDelivery', label: 'Code Postal'}
                          - { property: 'addressCountryDelivery', label: 'Pays'}
