version: '3'
services:
  app:
    build: .
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
  db:
    image: mysql:5.7
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: philippedesorbon
    volumes:
        - db_data:/var/lib/mysql
        - ./philippedesorbon.sql:/docker-entrypoint-initdb.d/philippedesorbon.sql
volumes:
  db_data:
