index:
    path: /
    controller: App\Controller\DefaultController::index

maison:
    path: /LaMaison
    controller: App\Controller\DefaultController::maison

savoirfaire:
    path: /SavoirFaire
    controller: App\Controller\DefaultController::savoirfaire

champagnes:
    path: /Champagnes
    controller: App\Controller\DefaultController::champagnes

champagne_show:
    path:     /Champagnes/{id}
    controller: App\Controller\DefaultController::champagneShow

vignoble:
    path: /Vignoble
    controller: App\Controller\DefaultController::vignoble

boutique:
    path: /Boutique
    controller: App\Controller\DefaultController::boutique

mentionslegales:
    path: /MentionsLegales
    controller: App\Controller\DefaultController::mentionslegales

contact:
    path: /Contact
    controller: App\Controller\DefaultController::contact

robotstxt:
    path: /robots.txt
    controller: App\Controller\DefaultController::robots

logout:
    path: /Logout

compte:
    path: /MonCompte

commande:
    path: /Commande
    controller: App\Controller\DefaultController::commande



