index:
    path: /
    controller: App\Controller\DefaultController::index

maison:
    path: /LaMaison
    controller: App\Controller\DefaultController::maison

savoirfaire:
    path: /SavoirFaire
    controller: App\Controller\DefaultController::savoirfaire

champagnes:
    path: /Champagnes
    controller: App\Controller\DefaultController::champagnes

champagne_show:
    path:     /Champagnes/{id}
    controller: App\Controller\DefaultController::champagneShow

vignoble:
    path: /Vignoble
    controller: App\Controller\DefaultController::vignoble

boutique:
    path: /Boutique
    controller: App\Controller\DefaultController::boutique

panier:
    path: /Panier
    controller: App\Controller\DefaultController::panier

mentionslegales:
    path: /MentionsLegales
    controller: App\Controller\DefaultController::mentionslegales

contact:
    path: /Contact
    controller: App\Controller\DefaultController::contact

logout:
    path: /Logout

commande:
    path: /Commande
    controller: App\Controller\DefaultController::commande

checkout:
    path: /Checkout
    controller: App\Controller\OrderController::checkout

order_validated:
    path: /CommandeValidee/{method}
    controller: App\Controller\OrderController::orderValidated

gastronomie:
    path: /Gastronomie/{plat}
    controller: App\Controller\DefaultController::gastronomie

sitemap:
    path: /sitemap.xml
    controller: App\Controller\GoogleController::sitemap

robotstxt:
    path: /robots.txt
    controller: App\Controller\GoogleController::robots





